### ISSUE TITLE
Issue on the repository server

### ISSUE THREAD

**Issue by jimmy9gag** [testobject/help#24]
Hey guys, 

I tried to contact you guys through twitter, but i don't use twitter so i didn't know if i was doing it correctly so i'll leave a issue here.

I kept failing to retrieve the dependencies, so i checked your repository server and found that i kept failing to retrieve any data from http://nexus.testobject.org/nexus/content/repositories/testobject-public-repo/

I would love to here some updates.

Thanks,
Kim

**Comment by hlenke** [comment]
Hi Kim,

Thanks for pointing out this issue. We'll have a look at this today.

Best,

Hannes

**Comment by jimmy9gag** [comment]
Dear Hannes,

Sure. thanks for the fast update! 

Hope it is not a big issue :+1:

**Comment by clample** [comment]
Hi Kim,

The issue should be resolved now.

Best,
Chris
