### ISSUE TITLE
Issue lanching my first TEST

### ISSUE THREAD

**Issue by repo-tests** [testobject/help#26]
Hi TestObject Support
Today i lanched my first test on TESTOBJECT platform after making the necessery setup using the link (Thanks for the very detailed articles) : "https://testobject.com/blog/2015/12/appium-advanced-test-setup.html" and creating an account on the platform using the userName : ​"QAEng", then I uploaded an apk (just for test) and get the apk id and suite id
I think everything is OK, but once i execute the test I get the error "A message body reader for Java class java.util.Set, and Java type interface java.util.Set, and MIME media type application/octet-stream was not found"
Did I miss something? Is it a known issue for TestObject Beginners?    
Thanks in advance for the help :)

**Comment by ragog** [comment]
Hi there,

how are you importing our API? Gradle, maven, or with a JAR? Which version are you using?

**Comment by repo-tests** [comment]
Hi ragog
Thanks for the quick reply, I'm importing the api using maven
....
	<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>3.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.testobject</groupId>
			<artifactId>testobject-appium-java-api</artifactId>
			<version>0.0.18</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>
....

**Comment by repo-tests** [comment]
The full stacktrace

1 * Client out-bound request
1 > GET https://app.testobject.com:443/api/appium/wd/hub/rest/appium/v1/suites/0/deviceIds
1 > Content-Type: application/json
1 > Authorization: Basic NDdFNjY4OUU1RjQxNEVERTkwNjdBMDcxOUMxODVCMzc6
1 * Client in-bound response
1 < 200
1 < Server: nginx
1 < Date: Sun, 01 May 2016 15:27:09 GMT
1 < Content-Length: 0
1 < Connection: keep-alive
1 < X-Frame-Options: ALLOW-FROM http://jenkins.testobject.org:9999/
1 < 
mai 01, 2016 4:27:08 PM com.sun.jersey.api.client.ClientResponse getEntity
GRAVE: A message body reader for Java class java.util.Set, and Java type interface java.util.Set, and MIME media type application/octet-stream was not found
mai 01, 2016 4:27:08 PM com.sun.jersey.api.client.ClientResponse getEntity
GRAVE: The registered message body readers compatible with the MIME media type are:
application/octet-stream ->
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.RenderedImageProvider
*/* ->
  com.sun.jersey.core.impl.provider.entity.FormProvider
  com.sun.jersey.core.impl.provider.entity.StringProvider
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$General
  com.sun.jersey.core.impl.provider.entity.ReaderProvider
  com.sun.jersey.core.impl.provider.entity.DocumentProvider
  com.sun.jersey.core.impl.provider.entity.SourceProvider$StreamSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$SAXSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$DOMSourceReader
  com.sun.jersey.json.impl.provider.entity.JSONJAXBElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONArrayProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONObjectProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootObjectProvider$General
  com.sun.jersey.core.impl.provider.entity.EntityHolderReader
  com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONListElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JacksonProviderProxy
  com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider

**Comment by ragog** [comment]
Are those all the dependencies you are importing into this project?

**Comment by repo-tests** [comment]
No, I don’t think that the other dependencies concern TestObject API, here i listed all the dependencies:


	<properties>
		<appium-client.version>3.3.0</appium-client.version>
		<appium-java.version>0.0.18</appium-java.version>
		<cglib.version>3.2.0</cglib.version>
		<guava.version>19.0</guava.version>
		<junit.version>4.12</junit.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>${guava.version}</version>
		</dependency>
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>${appium-client.version}</version>
		</dependency>
		<dependency>
			<groupId>org.testobject</groupId>
			<artifactId>testobject-appium-java-api</artifactId>
			<version>${appium-java.version}</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
		</dependency>
		<dependency>
			<groupId>cglib</groupId>
			<artifactId>cglib</artifactId>
			<version>${cglib.version}</version>
		</dependency>
	</dependencies>

**Comment by ragog** [comment]
Hi,

can you please share the test code with us at support@testobject.com?
We can solve this faster if we are able to reproduce the issue on our side ;)

**Comment by repo-tests** [comment]
Ok
**My Test Class**: (I’m only testing the access to the app, the test does not do anything interesting):





`
@TestObject(testLocally = false, testObjectApiKey = "47E6689E5F414EDE9067A0719C185B37", testObjectAppId=1,  testObjectApiEndpoint="https://app.testobject.com:443/api/appium/wd/hub")
@RunWith(TestObjectAppiumSuite.class)
public class NewFWTest extends AbstractTest {
 
    public NewFWTest() {}

    /* A simple addition, it expects the correct result to appear in the result field. */
    @Test
    public void clickOnNewsTest() throws InterruptedException {

    	System.out.println(true);
    	app.calculatorScreen.isItCorrect();
        assertTrue(app.calculatorScreen.isItCorrect());

    }

}

**my AbstractTest Class:**


``
public abstract class AbstractTest {
    /* Set the result watcher to send test results to testObject*/
    @Rule
    public TestObjectTestResultWatcher resultWatcher = new TestObjectTestResultWatcher();
    private AppiumDriver driver;
    protected Calculator app;
    /* Establish a connection to TestObject, or to a local device test is local */
    @Before
    public void connect() throws MalformedURLException{
        this.driver = AppiumDriverBuilder.forAndroid()
                .withApiKey(resultWatcher.getApiKey())
                .withTestReportId(resultWatcher.getTestReportId())
                .withEndPoint(new URL("https://app.testobject.com:443/api/appium/wd/hub")).build();
        resultWatcher.setAppiumDriver(driver);
        app = new Calculator(driver);
    }
    
}



**my AppiumDriverBuilder class:**



public abstract class AppiumDriverBuilder<RequiredElementType extends WebElement, Driver extends AppiumDriver<RequiredElementType>> {
    private static final String DEVICE_NAME_KEY = "deviceName";

    private String apiKey;
    private String testReportId;
    private URL endpoint; 
 
    /**
     * @param endpoint URL pointing to TESTOBJECT platform ;
     * @return AppiumDriverBuilder object after setting the endpoint URL 
     */
    public AppiumDriverBuilder<RequiredElementType, Driver> withEndPoint(final URL endpoint) {
        this.endpoint = endpoint;

        return this;
    }

    
    
    /**
     * @param apiKey
     * @return TestObject identifier for the app that the tests will be run on 
     */
    public AppiumDriverBuilder<RequiredElementType, Driver> withApiKey(final String apiKey) {
        this.apiKey = apiKey;
        return this;
    }

    /**
     * @param testReportId ID of the test report the results are to be associated with.
     * @return AppiumDriverBuilder after setting the report ID  
     */
    public AppiumDriverBuilder<RequiredElementType, Driver> withTestReportId(final String testReportId) {
        this.testReportId = testReportId;
        return this;
    }

    public abstract Driver build();
    
    

    /**
     * @return Dedicated driver for running tests on an Android device or emulator.
     * the driver returned are built from the endpoint and  desired capabilities 
     * of the AppiumDriverBuilder parent object 
     */
    public static AppiumDriverBuilder<AndroidElement, AndroidDriver<AndroidElement>> forAndroid() {
        return new AppiumDriverBuilder<AndroidElement, AndroidDriver<AndroidElement>>() {
            @Override
            public AndroidDriver<AndroidElement> build() {
                return new AndroidDriver<>(getEndpoint(), buildCapabilities());

            }
        };
    }

    /**
     * @return Dedicated driver for running tests on an iOS device or emulator.
     * the driver returned are built from the endpoint and  desired capabilities 
     * of the AppiumDriverBuilder parent object 
     */
    public static AppiumDriverBuilder<IOSElement, IOSDriver<IOSElement>> forIOS() {
        return new AppiumDriverBuilder<IOSElement, IOSDriver<IOSElement>>() {
            @Override
            public IOSDriver<IOSElement> build() {
                return new IOSDriver<>(getEndpoint(), buildCapabilities());

            }
        };
    }

    
    
    protected URL getEndpoint() {
        checkNotNull(endpoint);
        return endpoint;
    }

    
    /**
     * @return DesiredCapabilities built from TESTOBJECT keys (TESTOBJECT_API_KEY, TESTOBJECT_TEST_REPORT_ID,DEVICE_NAME_KEY)
     * s
     */
    protected DesiredCapabilities buildCapabilities() {
        checkNotNull(apiKey);
        checkNotNull(testReportId);
        final DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setCapability(TESTOBJECT_API_KEY, apiKey);
        capabilities.setCapability(TESTOBJECT_TEST_REPORT_ID, testReportId);

        capabilities.setCapability(DEVICE_NAME_KEY, "testDevice");
        return capabilities;
    }

}

**Comment by repo-tests** [comment]
Any news :) ?

**Comment by ragog** [comment]
Hello there,

you are not providing the suiteId in your annotation.

It currently looks like this:
@TestObject(testLocally = false, testObjectApiKey = "47E6689E5F414EDE9067A0719C185B37", testObjectAppId=1,  testObjectApiEndpoint="https://app.testobject.com:443/api/appium/wd/hub")

but it should look like

@TestObject(testObjectApiKey = "47E6689E5F414EDE9067A0719C185B37", testObjectSuiteId = 1234)

with testObjectSuiteId pointing to the id of the suite you have created through the TestObject interface.
Keep in mind the other parameters in the annotation are optional, so you don't need to specify them if you are just running a usual test on TestObject.
