### ISSUE TITLE
Search does not work on help pages

### ISSUE THREAD

**Issue by ritaryan** [testobject/help#27]
With no search functionality in Help, and no forum, it's tough to get quick answers to issues with the product.

**Comment by crummy** [comment]
Hi @ritaryan,

Thanks for the input, I'll log a feature request for this. In the meantime, you can restrict a google search to just our help pages by searching for `(search term) site:help.testobject.com`.

Malcolm

**Comment by crummy** [comment]
Sorry, I never noticed we actually do have a search feature. It also appears to be working to me. What behaviour you see when you try to use it?

**Comment by ragog** [comment]
Closing due to lack of feedback / not reproducible.
