### ISSUE TITLE
How to add multiple desired capabilities to setup suite? 

### ISSUE THREAD

**Issue by Sandarekha** [testobject/help#56]
Hi, I'm trying to run a test suite in TestObject.
I want to add device set here. 
But when I add capabilities I get errors in capabilities. 
Like this, 

The method getTestReportId() is undefined for the type TestObjectTestResultWatcher

![screen shot 2017-03-20 at 11 12 19 am](https://cloud.githubusercontent.com/assets/24934240/24089579/2706243c-0d5e-11e7-8c48-cc0e2b771548.png)

This is my script.. 

https://gist.github.com/Sandarekha/5ccdb596ecac512ed43540e9c0cc1067

How can I correct this?

**Comment by ragog** [comment]
This is not how you run Suites on TestObject. Please see our documentation for more information: https://help.testobject.com/docs/tools/appium/setups/suite-setup/junit
